#include <R.h>
#include <Rinternals.h>

/*
  Prototype declarations for all native routines in spatstat package

  Automatically generated - do not edit! 

*/

/*
  
                  Functions invoked by .C

*/

void areadifs(double *, int *, double *, double *, int *, int *, double *, void *); 
void areaBdif(double *, int *, double *, double *, int *, int *, double *, double *, double *, double *, double *, void *);
void delta2area(double *, double *, double *, double *, int *, double *, double *, double *, double *, int *, void *); 
void delta2area(double *, double *, double *, double *, int *, double *, double *, double *, double *, int *, void *);
void digberJ(double *, double *, int *, int *, int *, double *, void *);
void xysegint(int *, double *, double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, void *);
void Fclosepairs(int *, double *, double *, double *, int *, int *, int *, int *, double *, double *, double *, double *, double *, double *, double *, int *, void *); 
void paircount(int *, double *, double *, double *, int *, void *); 
void Fclosepairs(int *, double *, double *, double *, int *, int *, int *, int *, double *, double *, double *, double *, double *, double *, double *, int *, void *); 
void crosscount(int *, double *, double *, int *, double *, double *, double *, int *, void *); 
void Fcrosspairs(int *, double *, double *, int *, double *, double *, double *, int *, int *, int *, int *, double *, double *, double *, double *, double *, double *, double *, int *, void *);
void cocoImage(int *, int *, int *, void *); 
void cocoGraph(int *, int *, int *, int *, int *, int *, void *);
void lincrossdist(int *, double *, double *, int *, double *, double *, int *, double *, double *, double *, int *, int *, double *, int *, int *, double *, void *);
void trigrafS(int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, void *); 
void trigraf(int *, int *, int *, int *, int *, int *, int *, int *, int *, int *, void *); 
void Idist2dpath(int *, int *, int *, int *, int *, int *, int *, void *);
void Gdenspt(int *, double *, double *, double *, double *, void *); 
void Gwtdenspt(int *, double *, double *, double *, double *, double *, void *); 
void Gwtdenspt(int *, double *, double *, double *, double *, double *, void *); 
void denspt(int *, double *, double *, double *, double *, double *, void *); 
void wtdenspt(int *, double *, double *, double *, double *, double *, double *, void *); 
void wtdenspt(int *, double *, double *, double *, double *, double *, double *, void *); 
void adenspt(int *, double *, double *, double *, double *, double *, double *, void *); 
void awtdenspt(int *, double *, double *, double *, double *, double *, double *, double *, void *); 
void awtdenspt(int *, double *, double *, double *, double *, double *, double *, double *, void *); 
void crdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, void *); 
void wtcrdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void wtcrdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void acrdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void awtcrdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, void *); 
void awtcrdenspt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, void *);
void segdens(double *, int *, double *, double *, double *, double *, int *, double *, double *, double *, void *);
void Ediggra(int *, double *, double *, int *, int *, double *, double *, int *, double *, double *, double *, void *);
void Ediggatsti(int *, double *, double *, int *, int *, double *, double *, int *, double *, double *, void *);
void discareapoly(int *, double *, double *, int *, double *, int *, double *, double *, double *, double *, double *, double *, void *);
void Ddist2dpath(int *, double *, int *, double *, double *, int *, int *, void *);
void D3pairdist(int *, double *, double *, double *, int *, double *, void *); 
void D3pairPdist(int *, double *, double *, double *, double *, double *, double *, int *, double *, void *); 
void nnd3D(int *, double *, double *, double *, double *, int *, double *, void *); 
void knnd3D(int *, int *, double *, double *, double *, double *, int *, double *, void *); 
void nnw3D(int *, double *, double *, double *, double *, int *, double *, void *); 
void knnw3D(int *, int *, double *, double *, double *, double *, int *, double *, void *); 
void D3crossdist(int *, double *, double *, double *, int *, double *, double *, double *, int *, double *, void *); 
void D3crossPdist(int *, double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, int *, double *, void *);
void Cpairdist(int *, double *, double *, int *, double *, void *); 
void CpairPdist(int *, double *, double *, double *, double *, int *, double *, void *); 
void Ccrossdist(int *, double *, double *, int *, double *, double *, int *, double *, void *); 
void CcrossPdist(int *, double *, double *, int *, double *, double *, double *, double *, int *, double *, void *);
void nndMD(int *, int *, double *, double *, double *, void *); 
void knndMD(int *, int *, int *, double *, double *, double *, void *); 
void nnwMD(int *, int *, double *, double *, int *, double *, void *); 
void knnwMD(int *, int *, int *, double *, double *, int *, double *, void *);
void distmapbin(double *, double *, double *, double *, int *, int *, int *, double *, double *, void *);
void ripleybox(int *, double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void ripleypoly(int *, double *, double *, int *, double *, int *, double *, double *, double *, double *, double *, void *);
void exact_dt_R(double *, double *, int *, double *, double *, double *, double *, int *, int *, int *, int *, double *, int *, double *, void *);
void ps_exact_dt_R(double *, double *, double *, double *, int *, int *, int *, int *, int *, double *, int *, int *, double *, void *);
void fardist2grid(int *, double *, double *, int *, double *, double *, int *, double *, double *, double *, void *); 
void fardistgrid(int *, double *, double *, int *, double *, double *, int *, double *, double *, double *, void *);
void RcallK3(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, int *, double *, double *, double *, int *, void *); 
void RcallG3(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, int *, double *, double *, double *, int *, void *); 
void RcallF3(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, int *, int *, int *, void *); 
void RcallF3cen(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, int *, int *, int *, int *, int *, int *, void *); 
void RcallG3cen(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, int *, int *, int *, int *, int *, int *, int *, void *); 
void Rcallpcf3(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, int *, double *, double *, double *, int *, double *, void *); 
void RcallF3(double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, int *, int *, int *, void *);
void locxprod(int *, double *, double *, int *, double *, double *, double *, int *, double *, double *, void *);
void Efiksel(int *, double *, double *, int *, double *, double *, double *, double *, double *, void *);
void Egeyer(int *, double *, double *, int *, int *, double *, double *, int *, double *, double *, double *, void *);
void hasXclose(int *, double *, double *, double *, int *, void *); 
void hasXpclose(int *, double *, double *, double *, double *, int *, void *); 
void hasXYclose(int *, double *, double *, int *, double *, double *, double *, int *, void *); 
void hasXYpclose(int *, double *, double *, int *, double *, double *, double *, double *, int *, void *); 
void hasX3close(int *, double *, double *, double *, double *, int *, void *); 
void hasX3pclose(int *, double *, double *, double *, double *, double *, int *, void *); 
void hasXY3close(int *, double *, double *, double *, int *, double *, double *, double *, double *, int *, void *); 
void hasXY3pclose(int *, double *, double *, double *, int *, double *, double *, double *, double *, double *, int *, void *);
void Cidw(double *, double *, double *, int *, double *, double *, int *, double *, double *, int *, double *, double *, double *, double *, void *); 
void idwloo(double *, double *, double *, int *, double *, double *, double *, double *, void *);
void locprod(int *, double *, double *, double *, int *, double *, double *, void *); 
void locxprod(int *, double *, double *, int *, double *, double *, double *, int *, double *, double *, void *);
void KborderI(int *, double *, double *, double *, int *, double *, int *, int *, void *); 
void KborderD(int *, double *, double *, double *, int *, double *, double *, double *, void *); 
void Kwborder(int *, double *, double *, double *, double *, int *, double *, double *, double *, void *); 
void KnoneI(int *, double *, double *, int *, double *, int *, void *); 
void KnoneD(int *, double *, double *, int *, double *, double *, void *); 
void Kwnone(int *, double *, double *, double *, int *, double *, double *, void *); 
void KrectWtd(double *, double *, int *, double *, double *, double *, int *, double *, double *, int *, int *, int *, int *, double *, double *, double *, double *, double *, void *); 
void KrectInt(double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, int *, int *, double *, double *, int *, int *, int *, void *); 
void KrectDbl(double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, int *, int *, double *, double *, double *, double *, double *, void *);
void Csumouter(double *, int *, int *, double *, void *); 
void Cwsumouter(double *, int *, int *, double *, double *, void *); 
void Csum2outer(double *, double *, int *, int *, int *, double *, void *); 
void Cwsum2outer(double *, double *, int *, int *, int *, double *, double *); 
void Cquadform(double *, int *, int *, double *, double *, void *); 
void Cbiform(double *, double *, int *, int *, double *, double *, void *); 
void Csumsymouter(double *, int *, int *, double *, void *); 
void Cwsumsymouter(double *, double *, int *, int *, double *, void *);
void Ccountends(int *, double *, int *, double *, int *, double *, double *, int *, int *, int *, double *, double *, double *, int *, void *);
void Clinequad(int *, int *, int *, int *, double *, double *, double *, int *, int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, void *); 
void ClineRquad(int *, int *, int *, int *, double *, double *, double *, int *, int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, void *); 
void ClineMquad(int *, int *, int *, int *, double *, double *, double *, int *, int *, double *, double *, int *, int *, double *, double *, int *, double *, double *, int *, int *, double *, double *, int *, void *); 
void ClineRMquad(int *, int *, int *, int *, double *, double *, double *, int *, int *, double *, double *, int *, int *, double *, double *, int *, double *, double *, int *, int *, double *, double *, int *, void *);
void linearradius(int *, int *, int *, double *, int *, double *, double *, double *, void *); 
void cocoGraph(int *, int *, int *, int *, int *, int *, void *);
void cocoGraph(int *, int *, int *, int *, int *, int *, void *);
void Clixellate(int *, int *, int *, int *, int *, int *, double *, double *, int *, double *, int *, int *, int *, double *, int *, double *, void *);
void locpcfx(int *, double *, double *, int *, int *, double *, double *, int *, int *, double *, double *, double *, void *); 
void locWpcfx(int *, double *, double *, int *, int *, double *, double *, int *, double *, int *, double *, double *, double *, void *);
void cocoGraph(int *, int *, int *, int *, int *, int *, void *);
void minPnnd2(int *, double *, double *, double *, double *, void *); 
void minnnd2(int *, double *, double *, double *, double *, void *); 
void maxPnnd2(int *, double *, double *, double *, double *, void *); 
void maxnnd2(int *, double *, double *, double *, double *, void *);
void nnX3Dinterface(int *, double *, double *, double *, int *, int *, double *, double *, double *, int *, int *, int *, int *, double *, int *, double *, void *); 
void knnX3Dinterface(int *, double *, double *, double *, int *, int *, double *, double *, double *, int *, int *, int *, int *, int *, double *, int *, double *, void *);
void nnXinterface(int *, double *, double *, int *, int *, double *, double *, int *, int *, int *, int *, double *, int *, double *, void *); 
void knnXinterface(int *, double *, double *, int *, int *, double *, double *, int *, int *, int *, int *, int *, double *, int *, double *, void *);
void linnndist(int *, double *, double *, int *, double *, double *, int *, int *, int *, double *, int *, double *, double *, void *); 
void linknnd(int *, int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *); 
void linnnwhich(int *, double *, double *, int *, double *, double *, int *, int *, int *, double *, int *, double *, double *, int *, void *); 
void linknnd(int *, int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *); 
void linknncross(int *, int *, int *, double *, int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *); 
void linSnndwhich(int *, int *, double *, int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *); 
void linndcross(int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, int *, double *, int *, int *, double *, double *, int *, void *); 
void linndxcross(int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, int *, double *, int *, int *, int *, int *, double *, double *, int *, void *);
void nndistsort(int *, double *, double *, double *, double *, void *); 
void knndsort(int *, int *, double *, double *, double *, double *, void *); 
void nnwhichsort(int *, double *, double *, int *, double *, void *); 
void knnsort(int *, int *, double *, double *, double *, int *, double *, void *);
void Clinvwhichdist(int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *); 
void linvknndist(int *, int *, int *, double *, int *, int *, int *, int *, double *, double *, double *, double *, int *, void *);
void nnGinterface(int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, double *, int *, double *, void *); 
void knnGinterface(int *, double *, double *, int *, double *, double *, int *, double *, double *, int *, int *, int *, double *, int *, double *, void *);
void linpairdist(int *, double *, double *, int *, double *, double *, double *, int *, int *, double *, int *, double *, void *);
void poly2imA(int *, int *, double *, double *, int *, double *, int *, void *);
void xypsi(int *, double *, double *, double *, double *, double *, double *, double *, int *, int *, void *); 
void Cxypolyselfint(int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, void *);
void auctionbf(int *, int *, int *, double *, double *, int *, double *, void *); 
void dwpure(int *, int *, int *, int *, int *, int *, void *); 
void auctionbf(int *, int *, int *, double *, double *, int *, double *, void *); 
void dwpure(int *, int *, int *, int *, int *, int *, void *); 
void dinfty_R(int *, int *, int *, void *); 
void dwpure(int *, int *, int *, int *, int *, int *, void *); 
void dwpure(int *, int *, int *, int *, int *, int *, void *);
void seg2pixI(int *, double *, double *, double *, double *, int *, int *, int *, void *); 
void seg2pixL(int *, double *, double *, double *, double *, double *, double *, double *, int *, int *, double *, void *); 
void seg2pixN(int *, double *, double *, double *, double *, double *, int *, int *, double *, void *);
void xysegint(int *, double *, double *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, void *); 
void xysi(int *, double *, double *, double *, double *, int *, double *, double *, double *, double *, double *, int *, void *); 
void xysiANY(int *, double *, double *, double *, double *, int *, double *, double *, double *, double *, double *, int *, void *); 
void xysegXint(int *, double *, double *, double *, double *, double *, double *, double *, double *, double *, int *, void *); 
void xysxi(int *, double *, double *, double *, double *, double *, int *, void *);
void Corput(int *, int *, double *, void *);
void knownCif(char *, int *, void *);
void scantrans(double *, double *, int *, double *, double *, double *, double *, int *, int *, double *, int *, void *);
void Gsmoopt(int *, double *, double *, double *, int *, double *, double *, void *); 
void Gwtsmoopt(int *, double *, double *, double *, int *, double *, double *, double *, void *); 
void smoopt(int *, double *, double *, double *, int *, double *, double *, double *, void *); 
void wtsmoopt(int *, double *, double *, double *, int *, double *, double *, double *, double *, void *); 
void asmoopt(int *, double *, double *, double *, int *, double *, double *, double *, void *); 
void awtsmoopt(int *, double *, double *, double *, int *, double *, double *, double *, double *, void *); 
void crsmoopt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void wtcrsmoopt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, void *); 
void acrsmoopt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, void *); 
void awtcrsmoopt(int *, double *, double *, int *, double *, double *, double *, double *, double *, double *, double *, void *);
void CspaSumSymOut(int *, int *, int *, int *, int *, int *, double *, int *, double *, void *); 
void CspaWtSumSymOut(int *, int *, int *, int *, int *, int *, double *, int *, int *, int *, int *, double *, double *, void *);
void Ccrosspaircounts(int *, double *, double *, int *, double *, double *, double *, int *, void *); 
void Cclosepaircounts(int *, double *, double *, double *, int *, void *);
void poly2imI(double *, double *, int *, int *, int *, int *, void *); 
void bdrymask(int *, int *, int *, int *, void *); 
void discs2grid(int *, double *, double *, int *, double *, double *, int *, double *, double *, double *, int *, void *);
/*

             Functions invoked by .Call

*/
SEXP close3pairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP close3IJpairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP cross3pairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP cross3IJpairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP Vclosepairs(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP VcloseIJpairs(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP VcloseIJDpairs(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP Vcrosspairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP VcrossIJpairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP VcrossIJDpairs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP Vclosethresh(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP triograph(SEXP, SEXP, SEXP, SEXP); 
SEXP trioxgraph(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP triDgraph(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP triDRgraph(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP graphVees(SEXP, SEXP, SEXP, SEXP);
SEXP Cxysegint(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP CxysegXint(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP CxysegXint(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP thinjumpequal(SEXP, SEXP, SEXP, SEXP);
SEXP xmethas(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP xmethas(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP PerfectStrauss(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP PerfectHardcore(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP PerfectStraussHard(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP PerfectDiggleGratton(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP PerfectDGS(SEXP, SEXP, SEXP, SEXP, SEXP); 
SEXP PerfectPenttinen(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP Cwhist(SEXP, SEXP, SEXP, SEXP);
